import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getAllPostsForHome } from "./api/posts";

const Home: NextPage = () => {
  const [posts, setPosts] = useState();
  const [language, setLanguage] = useState("pl");

  useEffect(() => {
    getAllPostsForHome(language).then((data) => setPosts(data));
  }, [language]);

  return (
    <div className="">
      <Head>
        <title>UA Future</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div>
          <button onClick={() => setLanguage("pl")}>PL</button>
          <button onClick={() => setLanguage("en")}>EN</button>
          <button onClick={() => setLanguage("uk")}>UA</button>
        </div>
        <h1 className="">LOGO</h1>

        <div>
          <div>
            AKTUALNOŚCI
            {posts &&
              posts.map((post: any) => (
                <div key={post.title.rendered}>
                  <h2>{post.title.rendered}</h2>
                </div>
              ))}
          </div>
          <div>FORMULARZ</div>
          <div>ZBIORKI</div>
        </div>
        <div>KIM JESTEŚMY</div>
        <div>Z KIM WSPOŁPRACUJEMY</div>
      </main>
    </div>
  );
};

export default Home;
